# Generated by Django 2.2.7 on 2019-11-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191123_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revendedor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='user_permissions',
        ),
    ]
