# Generated by Django 2.2.7 on 2019-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cashback_porcentagem',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='Porcentagem de Cashback'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cashback_valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Cashback'),
        ),
    ]
