# Generated by Django 2.2.7 on 2019-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191124_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cashback_porcentagem',
            field=models.IntegerField(null=True, verbose_name='Porcentagem de Cashback'),
        ),
    ]
