# Generated by Django 2.2.7 on 2019-11-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191124_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='Status'),
        ),
    ]
