# Generated by Django 2.2.7 on 2019-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191124_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(default='Em validação', max_length=20, verbose_name='Status'),
        ),
    ]
