# Generated by Django 2.2.7 on 2019-11-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191124_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cashback_porcentagem',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cashback_valor',
        ),
    ]
